### ISSUE TITLE
Material Showcase

### ISSUE THREAD

**Issue by ghzmdr** [howtoinstallghost/allghostthemes#23]
### Theme Name

Material Showcase

### Theme Description

Ghost theme developed following Google's Material Design guidelines and style. Built with boldness of containers and clarity of content in mind

### Link to your live demo

http://blog.vincentdefeo.me

### Link to download/purchase page

https://github.com/ghzmdr/material-showcase-ghost-theme

### Number of columns

1

**Comment by ghzmdr** [comment]
Sorry the name is 'Material Showcase' ... damn autocorrect

**Comment by andyboutte** [comment]
Hey @ghzmdr.  Thanks for submitting your theme.  You caught me at a great time...I am in the middle of adding new themes right now.  I have just added your theme and it will be live in about 30 mins.

**Comment by ghzmdr** [comment]
Thanks Andy, tell me when it's done. I would appreciate some feedback since
this is the first theme I publish. Thank a lot and keep up the good work!

Il giorno Tue Feb 03 2015 at 07:20:47 Andy Boutte <notifications@github.com>
ha scritto:

**Comment by andyboutte** [comment]
Your theme is now up on allghostthemes.com:

http://www.allghostthemes.com/materiale-showcase/

**Comment by ghzmdr** [comment]
Thanks, just, please... update the name if possible, is Material Showcase
not 'Materiale' notice the ending 'e'. I couldn't update the issue

Il giorno Tue Feb 03 2015 at 07:44:34 Andy Boutte <notifications@github.com>
ha scritto:
