### ISSUE TITLE
Móri - A clean and responsive theme for ghost

### ISSUE THREAD

**Issue by gillisig** [howtoinstallghost/allghostthemes#41]
### Theme Name

Móri - A clean and responsive theme for ghost

### Theme Description

Enjoy writing blogs with this simple and responsive theme focused on the ghost principle, blogging. No complicated fancy stuff. Just a plug and play setup.

* Designed for a great reading experience
* Fully Responsive
* Full-width content images
* Valid HTML5 and CSS3
* Easy plug and play setup
* Supports Ghost 0.5.x
* Free future updates
* Multi-User Support

### Link to your live demo

http://mori.axe.is/

### Link to download/purchase page

https://creativemarket.com/axe/191840-Móri-Clean-and-Responsive

### Number of columns

1

**Comment by gillisig** [comment]
Thanks! There seems to be some problem with the image on the listing page though. Maybe because of the special character in its name "ó" ?

**Comment by dbalders** [comment]
your right, it is because of that. Was hoping it was a cdn issue, but it is a problem with that character. Ill try and see if I can find a fix. Thanks for letting me know

**Comment by gillisig** [comment]
No problem, thanks for putting my theme up!

**Comment by dbalders** [comment]
of course! sorry it took forever

**Comment by gillisig** [comment]
No worries, we are all busy ppl :smile:
