### ISSUE TITLE
Update for Steam

### ISSUE THREAD

**Issue by epistrephein** [howtoinstallghost/allghostthemes#46]
I have moved the demo of my theme Steam (http://www.allghostthemes.com/steam/) to this url:

https://steamthe.me

Also, the theme actually has comments or static menu built in, you just need to activate them (the instructions to do that are in the repository README).

Can you please update the page with these new informations?
Thanks a lot :)

**Comment by andyboutte** [comment]
Hey @epistrephein.  I have updated the link to the demo and the description.  Thanks for letting us know!

**Comment by epistrephein** [comment]
Thanks for your work! :)
